#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SPAM_REPO == "DEADLY-SPAM-BOT-2.0" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RlYWRseS1GaWdodGVycy9EZWFkbHktU3BhbS1Cb3QtMi4wL2FyY2hpdmUvT2ZmaWNpYWxTYW1lZXIuemlw" | base64 -d
    elif [[ $SPAM_REPO == "DEADLY-SPAM-BOT-2.0" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RlYWRseS1GaWdodGVycy9EZWFkbHktU3BhbS1Cb3QtMi4wL2FyY2hpdmUvT2ZmaWNpYWxTYW1lZXIuemlw" | base64 -d
    elif [[ $SPAM_REPO =~ $regex ]]
    then
        if [[ $SPAM_REPO_BRANCH ]]
        then
            echo "${SPAM_REPO}/archive/${SPAM_REPO_BRANCH}.zip"
        else
            echo "${SPAM_REPO}/archive/OfficialSameer.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RlYWRseS1GaWdodGVycy9EZWFkbHktU3BhbS1Cb3QtMi4wL2FyY2hpdmUvT2ZmaWNpYWxTYW1lZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="OfficialSameer.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting Deadly Bot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m OfficialSameer
}

start_bot
